version: '3'
networks:
  net:

services:
  ds-db:
    build:
      context: ./db
    ports:
      - 5432:5432
    networks:
      - net
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mydata:/var/lib/postgresql/data

  ds-consumer:
    build:
      context: ./consumer
    ports:
      - 3012:3012
    networks:
      - net

  ds-queue:
    build:
      context: ./queue
    ports:
      - 3011:3011
    networks:
      - net

  ds-producer:
    build:
      context: ./producer
    ports:
      - 3010:3010
    networks:
      - net

volumes:
  mydata:
    driver: local
